-- Drop tables generated by Hibernate's default snake_case naming.
-- Keep the CamelCase tables from db/mysql/apt_schema.sql (e.g. `ChungCus`, `CanHos`, ...).
--
-- Usage:
--   mysql -h 127.0.0.1 -P 3306 -u root apt < db/mysql/drop_snake_case_tables.sql

SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS `hoa_don_dich_vu_dich_vus`;
DROP TABLE IF EXISTS `hoa_don_dich_vus`;
DROP TABLE IF EXISTS `phieu_thus`;

DROP TABLE IF EXISTS `hinh_anh_dich_vus`;
DROP TABLE IF EXISTS `dich_vus`;

DROP TABLE IF EXISTS `hinh_anh_can_hos`;
DROP TABLE IF EXISTS `can_hos`;

DROP TABLE IF EXISTS `hinh_anh_chung_cus`;
DROP TABLE IF EXISTS `chung_cus`;

DROP TABLE IF EXISTS `cu_dans`;

DROP TABLE IF EXISTS `chat_members`;
DROP TABLE IF EXISTS `chat_messages`;

DROP TABLE IF EXISTS `password_reset_requests`;
DROP TABLE IF EXISTS `nguoi_dungs`;

DROP TABLE IF EXISTS `phan_anhs`;
DROP TABLE IF EXISTS `tin_tucs`;

SET FOREIGN_KEY_CHECKS = 1;

